### ISSUE TITLE
Delayed Delivery

### ISSUE THREAD

**Issue by mceraso** [mceraso/TweetPath#1]
Hi /cc @codepathreview I have fallen ill and will not be able to complete TweetPath by midnight tonight. I will complete by midnight tomorrow night

**Comment by minhchau273** [comment]
Hi Michael,

Please let me know when you complete this assignment.

Thanks,
Chau

**Comment by chieger** [comment]
Hi Michael,

We have still not received your assignment. Can you please update us with what is going on?

Thanks,
Charlie

**Comment by mceraso** [comment]
@minhchau273 @chieger 
Hi Chau and Charlie,

Thank you for your patience. The illness ended up being the flu and left me unable to work for 3-4 days. Yesterday was my last day recovering from it and so I'm getting back on track now. I've completed the walkthroughs and have updated the ReadMe with my current progress. I will begin UI work now.

Thank you,
Michael

**Comment by mceraso** [comment]
My gif includes my terminal because I've noticed an issue wherein my code does not save currentUser to nil upon logout but does deauthorize access tokens. Upon relaunch, the app goes straight to table view thinking that currentUser != nil and yet does not have any access tokens with which to pull the tweets. I thought this was an interesting issue that I'd like to debug

**Comment by chieger** [comment]
Hi Michael,

I'm sorry to hear you were not feeling well.

Is your app complete and ready for review?

Week 5 assignment will still need to be submitted by this weekend's
deadline as we will use your 1 last request for assignment 4.

Thanks,
Charlie

On Thu, Feb 25, 2016 at 2:06 PM, Michael Ceraso notifications@github.com
wrote:

> My gif includes my terminal because I've noticed an issue wherein my code
> does not save currentUser to nil upon logout but does deauthorize access
> tokens. Upon relaunch, the app goes straight to table view thinking that
> currentUser != nil and yet does not have any access tokens with which to
> pull the tweets. I thought this was an interesting issue that I'd like to
> debug
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mceraso/TweetPath/issues/1#issuecomment-189006626.

## 

_Charlie Hieger_
_Dean, CodePath University_
charlie@codepath.com
